name: CI
on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    continue-on-error: true
    container: 84codes/crystal:latest-ubuntu-noble
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Shards install
        run: shards install

      - name: Run ameba
        run: bin/ameba src spec

  spec:
    name: Spec
    runs-on: ubuntu-latest
    container: 84codes/crystal:latest-ubuntu-noble
    services:
      lavinmq:
        image: cloudamqp/lavinmq

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Shards install
        run: shards install

      - name: Spec
        run: crystal spec --order random
        env:
          AMQP_URL: amqp://lavinmq

  format:
    name: Formatting
    runs-on: ubuntu-latest
    container: 84codes/crystal:latest-ubuntu-noble
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Format check
        run: crystal tool format --check
