name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    container:
      image: 84codes/crystal:latest-alpine
    steps:
      - name: Install rsync
        run: apk add --no-cache rsync
      - uses: actions/checkout@v2
      - name: Build
        run:  crystal docs lib/amq-protocol/src/amq-protocol.cr src/amqp-client.cr
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          SINGLE_COMMIT: true
