name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - name: Install Build Dependencies
        run: apk add --update rsync
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: shards install --production
      - name: Build
        run:  crystal docs lib/amq-protocol/src/amq-protocol.cr src/amqp-client.cr
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          SINGLE_COMMIT: true
